### ISSUE TITLE
Error in line 6 "in <module>     import credentials ModuleNotFoundError: No module named 'credentials'

### ISSUE THREAD

**Issue by seffadribble** [kar731/Twitter-Response-Bot#1]
When I run the script in Terminal, this error appears:

Traceback (most recent call last):
  File "TweetResponder.py", line 6, in <module>
    import credentials
ModuleNotFoundError: No module named 'credentials'

**Comment by kar731** [comment]
You will need to make a credentials.py containing the following:
`CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_KEY = ""
ACCESS_SECRET = ""`
Be sure you insert your keys
